-- TB_DATA_PW_SBR1_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_SBR1_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_SBR1_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PSM2_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PSM2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PSM2_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_CL2_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_CL2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_CL2_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_TPA2_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_TPA2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_TPA2_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_AB2_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_AB2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_AB2_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PP_EPK5_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PP_EPK5_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PP_EPK5_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PP6_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PP6_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PP6_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PP7_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PP7_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PP7_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_HX_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_HX_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_HX_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_SKN_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_SKN_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_SKN_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PP1_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PP1_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PP1_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PSM1_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PSM1_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PSM1_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PR_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PR_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PR_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PE1_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PE1_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PE1_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_BP2_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_BP2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_BP2_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PP_AEK4_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PP_AEK4_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PP_AEK4_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_EPS1_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_EPS1_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_EPS1_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PE2_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PE2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PE2_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_AN2_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_AN2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_AN2_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_UNID3_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_UNID3_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_UNID3_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_HJ_TL_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_HJ_TL_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_HJ_TL_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PSM4_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PSM4_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PSM4_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PA2_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PA2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PA2_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PP_PK3_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PP_PK3_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PP_PK3_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_SBR2_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_SBR2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_SBR2_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_UNID2_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_UNID2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_UNID2_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_BP1_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_BP1_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_BP1_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PSM3_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PSM3_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PSM3_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_TPA3_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_TPA3_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_TPA3_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PET_KPC2_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PET_KPC2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PET_KPC2_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_EPS2_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_EPS2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_EPS2_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_SUKJITL01_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_SUKJITL01_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_SUKJITL01_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_SUKJITL02_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_SUKJITL02_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_SUKJITL02_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_SBR3_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_SBR3_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_SBR3_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_CL3_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_CL3_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_CL3_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_SALT_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_SALT_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_SALT_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_AN3_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_AN3_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_AN3_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PET2_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PET2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PET2_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_AB1_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_AB1_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_AB1_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_PSM5_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_PSM5_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_PSM5_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_SM_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_SM_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_SM_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_AA_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_AA_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_AA_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_TPA1_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_TPA1_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_TPA1_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_UNID1_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_UNID1_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_UNID1_SEQ"
    OWNER TO postgres;

-- TB_DATA_PW_MA_SEQ
CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_PW_MA_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_PW_MA_SEQ"
    OWNER TO postgres;