CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_EPS_MP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_EPS_MP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_SALT_HP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_SALT_HP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_SALT_LP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_SALT_LP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_KPC_FR_MP2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_KPC_FR_MP2_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_PR_MP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_PR_MP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_PR_LP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_PR_LP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_PA_FR_LP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_PA_FR_LP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_PA_HP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_PA_HP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_SM_MP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_SM_MP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_PSM_LP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_PSM_LP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_PSM_MP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_PSM_MP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_HX_LP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_HX_LP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_HX_FW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_HX_FW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_PP_PRI_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_PP_PRI_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_PP_MP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_PP_MP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_PP_LP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_PP_LP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_PE_HP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_PE_HP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_SBR_MP2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_SBR_MP2_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_SBR_MP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_SBR_MP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_SBR_LP1_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_SBR_LP1_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_AA_MP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_AA_MP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_AA_LP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_AA_LP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_BP_HP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_BP_HP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_SBR_LP2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_SBR_LP2_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_CL_HP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_CL_HP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_PE_DW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_PE_DW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_AA_FR_DW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_AA_FR_DW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_MA_FR_HP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_MA_FR_HP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_TPA_FR_MP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_TPA_FR_MP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_TPA_FR_LP1_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_TPA_FR_LP1_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_TPA_FR_LP2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_TPA_FR_LP2_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_TPA_FW2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_TPA_FW2_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_AB_DW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_AB_DW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_MA_FW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_MA_FW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_PR_FW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_PR_FW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_SM_FW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_SM_FW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_TPA_FW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_TPA_FW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_SALT_FW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_SALT_FW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_SM_DW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_SM_DW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_MA_DW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_MA_DW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_BP_FR_LP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_BP_FR_LP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_PE_FW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_PE_FW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_AA_FW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_AA_FW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_SALT_DW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_SALT_DW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_SKN_DW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_SKN_DW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_KPC_FR_MP4_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_KPC_FR_MP4_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_PSM_DW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_PSM_DW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_SKN_FW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_SKN_FW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_PP_FW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_PP_FW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_AN_FW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_AN_FW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_PA_FW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_PA_FW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_AA_DW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_AA_DW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_PP_DW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_PP_DW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_PA_DW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_PA_DW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_AN_DW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_AN_DW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_SFC_HP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_SFC_HP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_TPA_FR_SFC2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_TPA_FR_SFC2_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_TPA_FR_SFC1_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_TPA_FR_SFC1_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_AA_FR_FW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_AA_FR_FW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_SKN_HP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_SKN_HP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_SKP_HP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_SKP_HP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_SKP_PRI_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_SKP_PRI_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_WA_AB_FW_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_WA_AB_FW_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_UNID_HP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_UNID_HP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_PSM_LP2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_PSM_LP2_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_BK_MP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_BK_MP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_STAC_HP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_STAC_HP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_SFC_MP1_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_SFC_MP1_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_SFC_MP2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_SFC_MP2_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_HCC2_MP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_HCC2_MP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_TPA_FR_LP3_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_TPA_FR_LP3_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_TPA_FR_MP2_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_TPA_FR_MP2_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_TPA_FR_MP3_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_TPA_FR_MP3_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_TPA_FR_MP4_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_TPA_FR_MP4_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_SFCM_MP_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_SFCM_MP_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_USA_FR_PRI_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_USA_FR_PRI_SEQ"
    OWNER TO postgres;


CREATE SEQUENCE IF NOT EXISTS public."TB_DATA_ST_HP_FR_CL_SEQ"
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 1
    CYCLE;

ALTER SEQUENCE public."TB_DATA_ST_HP_FR_CL_SEQ"
    OWNER TO postgres;

