name: Push Email Notification

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract commit info
        id: commit
        run: |
          # 제목, 본문
          SUBJECT="$(git log -1 --pretty=%s)"
          BODY="$(git log -1 --pretty=%b)"

          echo "Full Subject: $SUBJECT"
          echo "Body: $BODY"

          # 접수와 구분
          if [[ "$SUBJECT" == reception_msg:* ]]; then
            CLEAN_SUBJECT="${SUBJECT#reception_msg:}"   # 구분값 날림.
            echo "mail_subject=$CLEAN_SUBJECT" >> $GITHUB_OUTPUT

            echo "mail_body=$BODY" >> $GITHUB_OUTPUT
            echo "match=Y" >> $GITHUB_OUTPUT
          else
            echo "match=N" >> $GITHUB_OUTPUT

          fi

      - name: Send mail on push
        if: steps.commit.outputs.match == 'Y'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "${{ steps.commit.outputs.mail_subject }}"
          to: "quristyle@gmail.com "
          from: "메시지봇"
          html_body: |
            <div>${{ steps.commit.outputs.mail_body }}</div>
