name: Push Email Notification

on:
  push:
    branches:
      - main 

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:



      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract commit info
        id: commit
        run: |
          # 제목, 본문
          SUBJECT="$(git log -1 --pretty=%s)"

          echo "Full Subject: $SUBJECT"

          # 접수와 구분
          if [[ "$SUBJECT" == reception_alert:* ]]; then
            echo "match=Y" >> $GITHUB_OUTPUT
          else if [[ "$SUBJECT" == reception_msg:* ]]; then
            echo "match=Y" >> $GITHUB_OUTPUT
          else
            echo "match=N" >> $GITHUB_OUTPUT
          fi






      - name: Send mail on push
        if: steps.commit.outputs.match == 'N'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "📬 [${{ github.event.head_commit.message }}] - ${{ github.actor }}"
          to: "quristyle@gmail.com, uspuni@gmail.com, utmost793@daum.net, anstnwl27@gmail.com, a0624z@naver.com "
          from: "hjmaintenance"
          html_body: |
            <!DOCTYPE html>
            <html lang="ko">
            <head>
              <meta charset="UTF-8">
              <title>GitHub Push Notification</title>
            </head>
            <body style="margin:0; padding:20px; font-family:Arial, sans-serif; background-color:#f4f4f7;">
              <div style="background-color:white; border:1px solid #0366d6; border-radius:12px; padding:20px; max-width:500px;">
                
                <!-- Header -->
                <div style="font-size:20px; font-weight:bold; color:#24292f; margin-bottom:20px; display:flex; align-items:center;">
                  <span style="margin-right:10px;">📢</span>
                  <span>GitHub Repository Push Notification</span>
                </div>

                <!-- Repository -->
                <div style="display:flex; align-items:center; margin-bottom:10px; line-height:1.2;">
                  <span style="width:28px; text-align:center; display:inline-block;">📂</span>
                  <strong style="color:#0366d6; width:130px; display:inline-block;">Repository:</strong>
                  <span>${{ github.repository }}</span>
                </div>

                <!-- Pushed by -->
                <div style="display:flex; align-items:center; margin-bottom:10px; line-height:1.2;">
                  <span style="width:28px; text-align:center; display:inline-block;">👤</span>
                  <strong style="color:#0366d6; width:130px; display:inline-block;">Pushed by:</strong>
                  <span>${{ github.actor }}</span>
                </div>

                <!-- Commit message -->
                <div style="display:flex; align-items:center; margin-bottom:10px; line-height:1.2;">
                  <span style="width:28px; text-align:center; display:inline-block;">📝</span>
                  <strong style="color:#0366d6; width:130px; display:inline-block;">Commit message:</strong>
                  <span>${{ github.event.head_commit.message }}</span>
                </div>

                <!-- Compare changes -->
                <div style="display:flex; align-items:center; margin-bottom:10px; line-height:1.2;">
                  <span style="width:28px; text-align:center; display:inline-block;">🔗</span>
                  <strong style="color:#0366d6; width:130px; display:inline-block;">Compare changes:</strong>
                  <a href="${{ github.event.compare }}" style="display:inline-block; padding:4px 8px; font-size:13px; background-color:#28a745; color:white; border-radius:5px; text-decoration:none; font-weight:bold;">View Changes</a>
                </div>

                <!-- Footer -->
                <div style="margin-top:20px; font-size:13px; color:#555; text-align:center;">
                  ✨ Take a peek at what’s new!
                </div>

              </div>
            </body>
            </html>