name: Push Email Notification

on:
  push:
    branches:
      - main 

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:



      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract commit info
        id: commit
        run: |
          # 제목, 본문
          SUBJECT="$(git log -1 --pretty=%s)"
          BODY="$(git log -1 --pretty=%B | sed ':a;N;$!ba;s/\n/<br>/g')"

          echo "Full Subject: $SUBJECT"

          # 접수와 구분
          if [[ "$SUBJECT" == reception_alert:* ]]; then
            echo "match=Y" >> $GITHUB_OUTPUT
          else
            
            if [[ "$SUBJECT" == reception_msg:* ]]; then
              echo "match=Y" >> $GITHUB_OUTPUT
            else
              echo "match=N" >> $GITHUB_OUTPUT
            fi

          fi






      - name: Send mail on push
        if: steps.commit.outputs.match == 'N'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "📬 [${{ github.event.head_commit.message }}] - ${{ github.actor }}"
          to: "anstnwl27@gmail.com, qwert7913@naver.com" #"quristyle@gmail.com, uspuni@gmail.com, utmost793@daum.net, anstnwl27@gmail.com, a0624z@naver.com "
          from: "hjmaintenance"
          html_body: |
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8">
              <title>GitHub Push Notification</title>
            </head>
            <body style="margin:0; padding:20px; font-family:Arial, sans-serif; background-color:#f4f4f7;">
              <table cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:500px; margin:0; padding:20px; background-color:#ffffff; border:1px solid #0366d6; border-radius:12px; box-shadow:0 4px 8px rgba(0,0,0,0.1); font-family:Arial, sans-serif;">
                
                <!-- Header -->
                <tr>
                  <td style="font-size:20px; font-weight:bold; color:#24292f; padding-bottom:15px;">
                    📢 GitHub Repository Push Notification
                  </td>
                </tr>

                <!-- Repository -->
                <tr>
                  <td style="padding-bottom:8px;">
                    <span style="display:inline-block; width:28px; text-align:center;">📂</span>
                    <strong style="color:#0366d6;">Repository:</strong>
                    <span>${{ github.repository }}</span>
                  </td>
                </tr>

                <!-- Pushed by -->
                <tr>
                  <td style="padding-bottom:8px;">
                    <span style="display:inline-block; width:28px; text-align:center;">👤</span>
                    <strong style="color:#0366d6;">Pushed by:</strong>
                    <span>${{ github.actor }}</span>
                  </td>
                </tr>

                <!-- Commit messages -->
                <tr>
                  <td style="padding-bottom:8px;">
                    <span style="display:inline-block; width:28px; text-align:center;">📝</span>
                    <strong style="color:#0366d6;">Commit messages:</strong>
                    <span>${{ steps.commit.outputs.mail_body }}</span>
                  </td>
                </tr>

                <!-- Compare changes -->
                <tr>
                  <td style="padding-bottom:8px;">
                    <span style="display:inline-block; width:28px; text-align:center; color:#0366d6;">🔗</span>
                    <strong style="color:#0366d6;">Compare changes:</strong>
                    <table cellpadding="0" cellspacing="0" border="0" style="display:inline-block; vertical-align:middle;">
                      <tr>
                        <td bgcolor="#28a745" style="border-radius:5px; text-align:center;">
                          <a href="${{ github.event.compare }}" style="display:block; padding:4px 8px; font-size:13px; color:#ffffff; text-decoration:none; font-weight:bold;">View Changes</a>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>

                <!-- Footer -->
                <tr>
                  <td style="padding-top:15px; font-size:13px; color:#555; text-align:center;">
                    ✨ Take a peek at what’s new!
                  </td>
                </tr>

              </table>
            </body>
            </html>